### ISSUE TITLE
Missing from Play Store

### ISSUE THREAD

**Issue by Erudition** [Thecave3/drone-ble-mesh#21]
The link to download the app is broken.

**Comment by Thecave3** [comment]
Hi, thanks for your interest in this project.
Unfortunately, the link on the play store is broken due to compliance with the new Google regulations regarding privacy that must be signed off.

At the current moment, we are not planning to upgrade it or maintain this application anymore, since it started as a proof of concept. 
You can try building up the project from the repo and see the application yourself.

**Comment by Erudition** [comment]
I would love to see it at least available on [F-Droid](https://f-droid.org/), if possible. It also supports custom repositories and you won't have to worry about the Google regulations.

Sad to see the project is being abandoned. Would love to have a working bluetooth mesh solution, yet I cannot find any anywhere.
